language: node_js
node_js:
- node
addons:
  chrome: stable
script: npm run all

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  skip_cleanup: true
  provider: script
  script: npm run lerna:publish
  on:
    os: linux
    node: 10
    branch: master
    tags: true
