name: CI

on:
  push: ~
  pull_request: ~
  schedule:
    - cron: '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
        java-version: ['openjdk@1.11']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{  matrix.java-version }}
      - run: npm ci
      - name: Lint & Build & Test
        run: npm run all
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: image-diffs
          path: packages/mutation-testing-elements/reports/diff/
